Update Jenkinsfile

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -20,29 +20,31 @@ pipeline {
           withCredentials([
             [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
           ]) {
-            withTool(name: 'packer1', type: 'biz.neustar.jenkins.plugins.packer.PackerInstallation') {
-              sh '''
-                set -e
-                export PATH=$PATH:${PACKER}
-
-                echo "Packer version:"
-                packer version
-
-                # Move to packer directory and build AMI
-                cd ../packer
-
-                packer build nginx_private_ami.json | tee packer-output.log
-
-                # Extract AMI ID
-                if [ -f ami_id.txt ]; then
-                  echo "AMI ID extracted from ami_id.txt"
-                elif grep -q 'ami-' packer-output.log; then
-                  grep -o 'ami-[a-zA-Z0-9\\-]*' packer-output.log | tail -1 > ami_id.txt
-                else
-                  echo "AMI ID not found!" && exit 1
-                fi
-              '''
+            script {
+              def packerHome = tool name: 'packer1'
+              env.PATH = "${packerHome}:${env.PATH}"
             }
+
+            sh '''
+              set -e
+
+              echo "Packer version:"
+              packer version
+
+              # Move to packer directory and build AMI
+              cd ../packer
+
+              packer build nginx_private_ami.json | tee packer-output.log
+
+              # Extract AMI ID
+              if [ -f ami_id.txt ]; then
+                echo "AMI ID extracted from ami_id.txt"
+              elif grep -q 'ami-' packer-output.log; then
+                grep -o 'ami-[a-zA-Z0-9\\-]*' packer-output.log | tail -1 > ami_id.txt
+              else
+                echo "AMI ID not found!" && exit 1
+              fi
+            '''
           }
         }
         archiveArtifacts artifacts: 'packer/packer-output.log, packer/ami_id.txt', onlyIfSuccessful: true
